In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
import os
from pathlib import Path
current_dir = Path(os.getcwd())

parent_dir = str(current_dir.parents[1])
#we will take as an example \Machine Learning A-Z Template Folder\Part 1 - Data Preprocessing\Data_Preprocessing
#make sure to take of the first \ because if it is left there then it is considered an absolute path...
data_url = r'Machine Learning A-Z Template Folder\Part 2 - Regression\Section 5 - Multiple Linear Regression\50_startups.csv'
path = os.path.join(parent_dir, data_url)

path

'D:\\Workspace\\machine-learning-study\\Machine Learning A-Z Template Folder\\Part 2 - Regression\\Section 5 - Multiple Linear Regression\\50_startups.csv'

In [3]:
data = pd.read_csv(path)
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
X = data.iloc[:, :-1].values
y = data.iloc[:, data.shape[1]-1].values

In [5]:
#first lets one hot encode this and take one out to avoid the dummy var trap
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 3] = labelencoder_X.fit_transform(X[:, 3])
onehotencoder = OneHotEncoder(categorical_features = [3]) # we give it the cols where we want the encoding to happen
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
X_train, X_test, y_train, y_test

(array([[  1.00000000e+00,   0.00000000e+00,   5.54939500e+04,
           1.03057490e+05,   2.14634810e+05],
        [  0.00000000e+00,   1.00000000e+00,   4.60140200e+04,
           8.50474400e+04,   2.05517640e+05],
        [  1.00000000e+00,   0.00000000e+00,   7.53288700e+04,
           1.44135980e+05,   1.34050070e+05],
        [  0.00000000e+00,   0.00000000e+00,   4.64260700e+04,
           1.57693920e+05,   2.10797670e+05],
        [  1.00000000e+00,   0.00000000e+00,   9.17491600e+04,
           1.14175790e+05,   2.94919570e+05],
        [  1.00000000e+00,   0.00000000e+00,   1.30298130e+05,
           1.45530060e+05,   3.23876680e+05],
        [  1.00000000e+00,   0.00000000e+00,   1.19943240e+05,
           1.56547420e+05,   2.56512920e+05],
        [  0.00000000e+00,   1.00000000e+00,   1.00023000e+03,
           1.24153040e+05,   1.90393000e+03],
        [  0.00000000e+00,   1.00000000e+00,   5.42050000e+02,
           5.17431500e+04,   0.00000000e+00],
        [  0.000000

In [7]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)
X_train, X_test

(array([[ 1.73205081, -0.73379939, -0.35006454, -0.78547109,  0.1011968 ],
        [-0.57735027,  1.36277029, -0.55530319, -1.48117426,  0.02734979],
        [ 1.73205081, -0.73379939,  0.07935762,  0.80133381, -0.55152132],
        [-0.57735027, -0.73379939, -0.54638238,  1.32505817,  0.07011684],
        [ 1.73205081, -0.73379939,  0.43485371, -0.35598663,  0.75148516],
        [ 1.73205081, -0.73379939,  1.26943143,  0.85518519,  0.98603118],
        [ 1.73205081, -0.73379939,  1.04525007,  1.28077047,  0.4404    ],
        [-0.57735027,  1.36277029, -1.529843  ,  0.02942065, -1.6218751 ],
        [-0.57735027,  1.36277029, -1.53976251, -2.76767264, -1.6372965 ],
        [-0.57735027,  1.36277029, -0.13115188,  1.14497701, -0.76949991],
        [-0.57735027,  1.36277029,  0.92791613, -0.02992062,  0.48303162],
        [ 1.73205081, -0.73379939, -0.20932933, -0.2993768 , -0.89915412],
        [-0.57735027, -0.73379939, -0.17870828,  0.2251352 , -1.26401642],
        [-0.57735027, -0.

In [8]:
from sklearn.linear_model import LinearRegression

regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
y_pred = regressor.predict(X_test)

In [10]:
import statsmodels.formula.api as sm
#X = np.insert(arr=X, obj=0, values=np.ones((X.shape[0], 1)).astype(int), axis=1)
X = np.append(arr=np.ones((X.shape[0],1)).astype(int), values=X, axis=1)

In [11]:
np.set_printoptions(precision=3)
X

array([[  1.000e+00,   0.000e+00,   1.000e+00,   1.653e+05,   1.369e+05,
          4.718e+05],
       [  1.000e+00,   0.000e+00,   0.000e+00,   1.626e+05,   1.514e+05,
          4.439e+05],
       [  1.000e+00,   1.000e+00,   0.000e+00,   1.534e+05,   1.011e+05,
          4.079e+05],
       [  1.000e+00,   0.000e+00,   1.000e+00,   1.444e+05,   1.187e+05,
          3.832e+05],
       [  1.000e+00,   1.000e+00,   0.000e+00,   1.421e+05,   9.139e+04,
          3.662e+05],
       [  1.000e+00,   0.000e+00,   1.000e+00,   1.319e+05,   9.981e+04,
          3.629e+05],
       [  1.000e+00,   0.000e+00,   0.000e+00,   1.346e+05,   1.472e+05,
          1.277e+05],
       [  1.000e+00,   1.000e+00,   0.000e+00,   1.303e+05,   1.455e+05,
          3.239e+05],
       [  1.000e+00,   0.000e+00,   1.000e+00,   1.205e+05,   1.487e+05,
          3.116e+05],
       [  1.000e+00,   0.000e+00,   0.000e+00,   1.233e+05,   1.087e+05,
          3.050e+05],
       [  1.000e+00,   1.000e+00,   0.000e+00,   1

In [12]:
SL = 0.05 # significance level

X_indecies = [0,1,2,3,4,5]
X_opt = X[:, X_indecies]
regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()
while max(regressor_OLS.pvalues) > SL:
    large_pvalue = np.where(regressor_OLS.pvalues==max(regressor_OLS.pvalues))[0][0]
    print(large_pvalue)
    X_indecies.remove(large_pvalue)
    X_indecies = list(map(lambda x: x-1 if x> large_pvalue else x, X_indecies))
    X_opt = X[:, X_indecies]
    regressor_OLS = sm.OLS(endog=y, exog=X_opt).fit()


X_opt

2
2
2
2
1


array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.]])

[1, 2, 3, 4, 5, 5, 6]